feat: 🎸 bin: update phpenv-install

diff --git a/bin/phpenv-install b/bin/phpenv-install
--- a/bin/phpenv-install
+++ b/bin/phpenv-install
@@ -1,18 +1,24 @@
 #!/bin/sh
 
-if [ $# -eq 0 ]; then
+if [ $# -eq 0 ] ; then
     echo "Usage: phpenv-install <version> [extensions]"
     exit 1
 else
     VERSION=$1
 fi
 
-EXTENSIONS=${2:-apcu=@ imagick=@}
+if [ $# -eq 1 ] ; then
+    EXTENSIONS="apcu=@ imagick=@"
+else
+    EXTENSIONS=""
+fi
 
-# 7.0-
-if [[ $VERSION =~ ^(7\.0\..+|[0-6]\..+)$ ]] ; then
-    echo "Invalid version: only 7.1+ are available"
-    exit 1
+# 7.3+
+if [[ $VERSION =~ ^(7\.[^3-9]\..+|7\.[1-9][0-9]+\..+|[89]\..+|[1-9][0-9]+\..+)$ ]] ; then
+    export PHP_BUILD_INSTALL_EXTENSION="$EXTENSIONS"
+    export PHP_BUILD_EXTRA_MAKE_ARGUMENTS=-j4
+    export PHP_BUILD_CONFIGURE_OPTS="--with-zlib-dir=/usr/local/opt/zlib --with-bz2=/usr/local/opt/bzip2 --with-jpeg-dir=/usr/local/opt/libjpeg --with-png-dir=/usr/local/opt/libpng --with-curl=/usr/local/opt/curl --with-iconv=/usr/local/opt/libiconv --with-libedit=/usr/local/opt/libedit"
+    phpenv install $VERSION
 # 7.1, 7.2
 elif [[ $VERSION =~ ^(7\.1\..+|7\.2\..+)$ ]] ; then
     sudo xcode-select --switch /Applications/Xcode.11.7.app
@@ -24,12 +30,21 @@ elif [[ $VERSION =~ ^(7\.1\..+|7\.2\..+)$ ]] ; then
     phpenv install $VERSION
 
     sudo xcode-select --switch /Library/Developer/CommandLineTools/
-# 7.3+
-else
+# 5.6, 7.0
+elif [[ $VERSION =~ ^(5\.6\..+|7\.0\..+)$ ]] ; then
+    sudo xcode-select --switch /Applications/Xcode.11.7.app
+    export SDKROOT=macosx
+
     export PHP_BUILD_INSTALL_EXTENSION="$EXTENSIONS"
     export PHP_BUILD_EXTRA_MAKE_ARGUMENTS=-j4
-    export PHP_BUILD_CONFIGURE_OPTS="--with-zlib-dir=/usr/local/opt/zlib --with-bz2=/usr/local/opt/bzip2 --with-jpeg-dir=/usr/local/opt/libjpeg --with-png-dir=/usr/local/opt/libpng --with-curl=/usr/local/opt/curl --with-iconv=/usr/local/opt/libiconv --with-libedit=/usr/local/opt/libedit"
+    export PHP_BUILD_CONFIGURE_OPTS="--with-zlib-dir=/usr/local/opt/zlib --with-bz2=/usr/local/opt/bzip2 --with-jpeg-dir=/usr/local/opt/libjpeg --with-png-dir=/usr/local/opt/libpng --with-curl=/usr/local/opt/curl --with-iconv=/usr/local/opt/libiconv --with-libedit=/usr/local/opt/libedit --without-tidy"
     phpenv install $VERSION
+
+    sudo xcode-select --switch /Library/Developer/CommandLineTools/
+# 5.5-
+else
+    echo "Invalid version: only 5.6+ are available"
+    exit 1
 fi
 
 gsed -i -E "s/^;?(max_execution_time) *=.*$/\1 = 0/g" ~/.phpenv/versions/$VERSION/etc/php.ini
